# Generated by Django 5.2 on 2025-08-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_codigorecuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopropio',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('viewer', 'Visualizador')], default='viewer', max_length=10),
        ),
    ]
