# Generated by Django 5.2 on 2025-08-28 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usuariopropio_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacion', models.CharField(max_length=8)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Administrador',
                'verbose_name_plural': 'Solicitudes de Administrador',
            },
        ),
    ]
