# Generated by Django 5.2 on 2025-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_solicitudadministrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopropio',
            name='codigo_pais',
            field=models.CharField(default='CO', help_text='Código del país para el teléfono (ej: CO, US, MX)', max_length=5),
        ),
    ]
