# Generated by Django 5.2 on 2026-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_usuariopropio_codigo_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopropio',
            name='calificacion_promedio',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='usuariopropio',
            name='disponible',
            field=models.BooleanField(default=False, help_text='Si el conductor está disponible para recibir viajes'),
        ),
        migrations.AddField(
            model_name='usuariopropio',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='usuariopropio',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Última latitud conocida', null=True),
        ),
        migrations.AddField(
            model_name='usuariopropio',
            name='licencia',
            field=models.CharField(blank=True, help_text='Número de licencia de conducción', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuariopropio',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Última longitud conocida', null=True),
        ),
        migrations.AlterField(
            model_name='usuariopropio',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('pasajero', 'Pasajero'), ('conductor', 'Conductor')], default='pasajero', max_length=15),
        ),
    ]
