# Generated by Django 5.2 on 2026-05-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('zona_origen', models.CharField(choices=[('Ubaté', 'Ubaté'), ('Cucunubá', 'Cucunubá'), ('Sutatausa', 'Sutatausa'), ('Tausa', 'Tausa'), ('Fúquene', 'Fúquene'), ('Susa', 'Susa'), ('Simijaca', 'Simijaca'), ('Carmen de Carupa', 'Carmen de Carupa'), ('Guachetá', 'Guachetá'), ('Lenguazaque', 'Lenguazaque')], max_length=50)),
                ('zona_destino', models.CharField(choices=[('Ubaté', 'Ubaté'), ('Cucunubá', 'Cucunubá'), ('Sutatausa', 'Sutatausa'), ('Tausa', 'Tausa'), ('Fúquene', 'Fúquene'), ('Susa', 'Susa'), ('Simijaca', 'Simijaca'), ('Carmen de Carupa', 'Carmen de Carupa'), ('Guachetá', 'Guachetá'), ('Lenguazaque', 'Lenguazaque')], max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base en COP', max_digits=10)),
                ('precio_por_km', models.DecimalField(decimal_places=2, default=1800, help_text='Precio por kilómetro en COP', max_digits=10)),
                ('recargo_nocturno', models.DecimalField(decimal_places=2, default=20, help_text='Porcentaje de recargo nocturno', max_digits=5)),
                ('recargo_festivo', models.DecimalField(decimal_places=2, default=15, help_text='Porcentaje de recargo en festivos', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'T004Tarifa',
                'ordering': ['zona_origen', 'zona_destino'],
                'unique_together': {('zona_origen', 'zona_destino')},
            },
        ),
    ]
