# Generated by Django 5.2 on 2026-05-04 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('origen_direccion', models.CharField(max_length=300)),
                ('origen_lat', models.FloatField()),
                ('origen_lng', models.FloatField()),
                ('destino_direccion', models.CharField(max_length=300)),
                ('destino_lat', models.FloatField()),
                ('destino_lng', models.FloatField()),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado'), ('en_curso', 'En Curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('tarifa_estimada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarifa_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_km', models.FloatField(default=0)),
                ('duracion_min', models.IntegerField(default=0)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata')], default='efectivo', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptado', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_cancelados', to=settings.AUTH_USER_MODEL)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_como_conductor', to=settings.AUTH_USER_MODEL)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_como_pasajero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'db_table': 'T003Viaje',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
