# Generated by Django 5.2 on 2026-05-04 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('tipo', models.CharField(choices=[('sedan', 'Sedán'), ('camioneta', 'Camioneta'), ('van', 'Van'), ('suv', 'SUV')], default='sedan', max_length=20)),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(limit_choices_to={'rol': 'conductor'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'T002Vehiculo',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
